import createError from "../utils/createError";

export const createOrder = async (req, res, next) => {
  try {
  } catch (err) {
    next(err);
  }
};

export const getOrders = async (req, res, next) => {
  try {
  } catch (err) {
    next(err);
  }
};
